/**
 * Timing Constants
 * Centralized timing values used throughout the application
 */

export const TIMING = {
  // Step durations (milliseconds)
  STEP_DURATION_STOP: 2000,
  STEP_DURATION_PULL: 5000,
  STEP_DURATION_REMOVE: 1500,
  STEP_DURATION_CREATE: 2000,
  STEP_DURATION_START: 2000,
  STEP_DURATION_WAIT_NETWORK: 10000,
  STEP_DURATION_WAIT_READY: 10000,
  STEP_DURATION_WAIT_READY_SHORT: 5000,
  STEP_DURATION_CLEANUP: 3000,
  STEP_DURATION_RECREATE: 5000,
  STEP_DURATION_START_DEPENDENTS: 3000,

  // Minimum visibility
  MIN_STEP_DURATION: 1000,
  INITIAL_RENDER_DELAY: 100,
  FINAL_STEP_DELAY: 800,

  // Reconnection
  RECONNECT_MAX_WAIT: 120000, // 2 minutes
  RECONNECT_POLL_INTERVAL: 3000, // 3 seconds

  // UI feedback
  CHECKMARK_DISPLAY_TIME: 3000,
  SUCCESS_DISPLAY_TIME: 5000,
};
