/**
 * Container Config Builder
 *
 * ONE shared builder used to recreate BOTH the upgraded target and its
 * network_mode dependents. It uses a "passthrough + strip + mutate" strategy
 * instead of an allow-list:
 *   - deep-copy the inspected Config and HostConfig,
 *   - delete only runtime-only keys (stale container IDs / host paths),
 *   - set the new Image (and, for dependents, the new NetworkMode),
 *   - for shared-network consumers strip the fields Docker forbids
 *     (PortBindings / PublishAllPorts / ExposedPorts / Hostname).
 *
 * Everything else — Healthcheck, User, Mounts, Sysctls, Dns, Devices, CapAdd,
 * StopSignal, StopTimeout, Ulimits, … — passes through untouched. This is the
 * fix for the config-drift / lost-healthcheck defect (PLAN-2 §0.1(c)).
 */

// HostConfig keys that describe the *previous* container instance and must never
// be sent back to Docker create (they embed stale IDs / host paths).
const RUNTIME_ONLY_HOSTCONFIG_KEYS = [
  "ContainerIDFile",
  "ResolvConfPath",
  "HostnamePath",
  "HostsPath",
  "RestartCount",
];

/**
 * Deep-clone a JSON-serializable object (Config / HostConfig are plain data).
 * @param {Object|undefined} obj
 * @returns {Object}
 */
function deepClone(obj) {
  if (!obj) {
    return {};
  }
  return structuredClone(obj);
}

/**
 * Docker auto-generates MAC addresses in the 02:42:* range. A stale one would
 * collide, so drop it and let Docker assign a fresh one. A user-defined MAC
 * (any other prefix) is preserved.
 * @param {*} mac
 * @returns {boolean}
 */
function isAutoGeneratedMac(mac) {
  return typeof mac === "string" && /^02:42:/i.test(mac);
}

/**
 * Whether a network mode makes the container a shared-network consumer
 * (it joins another container's/service's network namespace).
 * @param {string} networkMode
 * @returns {boolean}
 */
function isSharedNetworkMode(networkMode) {
  return (
    typeof networkMode === "string" &&
    (networkMode.startsWith("service:") || networkMode.startsWith("container:"))
  );
}

/**
 * Build a Docker create body from an inspected container.
 * @param {Object} params
 * @param {Object} params.inspect - Full Docker inspect JSON of the container.
 * @param {string} params.newImage - Image the recreated container should run.
 * @param {string} [params.networkMode] - Override NetworkMode (used for dependents,
 *   e.g. `container:<new-target-id>`). When omitted the original NetworkMode is kept.
 * @returns {{ containerConfig: Object, isSharedNetworkMode: boolean }}
 */
function buildCreateConfig({ inspect, newImage, networkMode }) {
  const config = deepClone(inspect && inspect.Config);
  const hostConfig = deepClone(inspect && inspect.HostConfig);

  config.Image = newImage;

  // Apply NetworkMode override (dependents point at the new target id).
  if (networkMode) {
    hostConfig.NetworkMode = networkMode;
  }
  const effectiveNetworkMode = hostConfig.NetworkMode || "";
  const shared = isSharedNetworkMode(effectiveNetworkMode);

  // Strip runtime-only HostConfig keys (stale container id / host paths).
  for (const key of RUNTIME_ONLY_HOSTCONFIG_KEYS) {
    delete hostConfig[key];
  }

  // Hostname defaults to the container's short id; drop that so the new
  // container gets a fresh one. A user-defined hostname (anything other than
  // the old short id) is preserved.
  const oldShortId = inspect && inspect.Id ? inspect.Id.substring(0, 12) : null;
  if (config.Hostname && oldShortId && config.Hostname === oldShortId) {
    delete config.Hostname;
  }

  // Drop auto-generated MAC so Docker assigns a fresh one.
  if (isAutoGeneratedMac(config.MacAddress)) {
    delete config.MacAddress;
  }
  if (hostConfig && isAutoGeneratedMac(hostConfig.MacAddress)) {
    delete hostConfig.MacAddress;
  }

  // Shared-network consumers cannot own ports or a hostname — those live on the
  // network provider. Docker rejects create requests that include them.
  if (shared) {
    delete hostConfig.PortBindings;
    delete hostConfig.PublishAllPorts;
    delete config.ExposedPorts;
    delete config.Hostname;
  }

  config.HostConfig = hostConfig;

  // Preserve explicit network attachments for non-shared containers only.
  const networkingConfig = shared ? undefined : buildNetworkingConfig(inspect);
  if (networkingConfig) {
    config.NetworkingConfig = networkingConfig;
  }

  return { containerConfig: config, isSharedNetworkMode: shared };
}

/**
 * Build a NetworkingConfig (EndpointsConfig) from inspected NetworkSettings,
 * keeping only the fields Docker create accepts. Returns undefined when there is
 * nothing meaningful to attach.
 * @param {Object} inspect
 * @returns {Object|undefined}
 */
function buildNetworkingConfig(inspect) {
  const networks = inspect && inspect.NetworkSettings && inspect.NetworkSettings.Networks;
  if (!networks) {
    return undefined;
  }

  const endpointsConfig = {};
  for (const [name, data] of Object.entries(networks)) {
    if (!data || typeof data !== "object") {
      continue;
    }
    const endpoint = {};
    if (data.IPAMConfig && Object.keys(data.IPAMConfig).length > 0) {
      endpoint.IPAMConfig = data.IPAMConfig;
    }
    if (Array.isArray(data.Links) && data.Links.length > 0) {
      endpoint.Links = data.Links;
    }
    if (Array.isArray(data.Aliases) && data.Aliases.length > 0) {
      endpoint.Aliases = data.Aliases;
    }
    if (Object.keys(endpoint).length > 0) {
      endpointsConfig[name] = endpoint;
    }
  }

  if (Object.keys(endpointsConfig).length === 0) {
    return undefined;
  }
  return { EndpointsConfig: endpointsConfig };
}

module.exports = {
  buildCreateConfig,
  buildNetworkingConfig,
  isSharedNetworkMode,
};
